# minimal mistakes Jekyll reference
# https://github.com/mmistakes/minimal-mistakes/blob/master/docs/_config.yml

remote_theme: mmistakes/minimal-mistakes

minimal_mistakes_skin: "air"

title: "Myzhar & MyzharBot"
subtitle: ":brain: Beyond Perception - Beyond Robotics :robot:"
name: &name "Walter Lucetti"
description: &description "Insights, projects, and stories about seeing, thinking, and moving machines."
url: "https://myzhar.tech"
repository: "Myzhar/myzhar.github.io/"
teaser: "assets/images/MyzharbotLogo.png"
logo: "assets/images/MyzharbotLogo_transparent.png"

search: true
search_full_content: true
breadcrumbs: true  # disabled by default
enable_copy_code_button: true


github: [metadata]

social:
  links: # An array of links to social media profiles
    - "https://linktr.ee/myzhar"
    - "https://instagram.com/myzharbot"
    - "https://www.linkedin.com/in/walterlucetti/"

analytics:
  provider: "google-gtag"
  google:
    tracking_id: "G-PYMBS7K65Z"
    anonymize_ip: true # default

# Site Footer
footer:
  since: "2025"
  links:
    - label: "Home"
      icon: "fas fa-fw fa-home"
      url: "https://myzhar.tech"
    - label: "LinkTree"
      icon: "fab fa-fw fa-linktree"
      url: "https://linktr.ee/myzhar"
    - label: "Instagram"
      icon: "fab fa-fw fa-instagram"
      url: "https://instagram.com/myzharbot"
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/walterlucetti/"
    - label: "Github"
      icon: "fab fa-fw fa-github-square"
      url: "https://github.com/myzhar"
    - label: "YouTube"
      icon: "fab fa-fw fa-youtube"
      url: "https://www.youtube.com/@myzhar"
    - label: "TikTok"
      icon: "fab fa-fw fa-tiktok"
      url: "https://tiktok.com/@myzhar"
    - label: "Threads"
      icon: "fab fa-fw fa-threads"
      url: "https://www.threads.com/@myzharbot"
    - label: "Email"
      icon: "fas fa-fw fa-envelope-square"
      url: "mailto:info@myzhar.com"
    - label: "Terms of Service"
      icon: "fas fa-fw fa-file-contract"
      url: "/terms/"


# Reading Files
include:
  - .htaccess
  - _pages
exclude:
  - README.md
  - LICENSE
  - Gemfile
  - vendor

# Build settings
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false

collections:
  projects:
    output: true
    permalink: /:collection/:path/
  events:
    output: true
    permalink: /:collection/:path/
  tutorials:
    output: true
    permalink: /:collection/:path/

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      share: true
      related: true
      show_date: true
  # _info
  - scope:
      path: ""
      type: info
    values:
      layout: single
      author_profile: true
      share: true
      read_time: false
  # _projects
  - scope:
      path: ""
      type: projects
    values:
      layout: single
      author_profile: true
      share: true
      read_time: true
  # _tutorials
  - scope:
      path: ""
      type: tutorials
    values:
      layout: single
      author_profile: true
      share: true
      read_time: true
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true

# Outputting
permalink: /:categories/:title/
paginate: 6 # amount of posts to show
paginate_path: /page:num/
# timezone: # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones

# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache
  - jekyll-redirect-from


# mimic GitHub Pages with --safe
whitelist:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache
  - jekyll-redirect-from

category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/

after_footer_scripts :
  #- /assets/js/cookie-consent.js
  - /assets/js/copyCode.js
